In [234]:
import requests
from bs4 import BeautifulSoup

request=requests.get("https://www.century21.com/real-estate/london-ky/LCKYLONDON/") #page 1

data=request.content
soup=BeautifulSoup(data, "html.parser")
# soup.prettify
all=soup.find_all("div")
# print(all)

In [235]:
all=soup.find_all("div", {"id":"results-container"}) #all search

#each card 
#getting the first card
card=soup.find_all("div", {"class":"property-card-primary-info"})
# card

In [236]:
l=[]

for item in card:
    d={} #when dictionary is global the on each iteration, the dictionary contents gets replaced so you end up with only one data

    d["Addresses"]=(item.find_all("div", {"class": "property-address"})[0].text.replace("\n", "").replace(" ",''))
    
    d["Beds"]=(item.find("div", {"class":"property-beds"}).find("strong").text.replace("\n", "").replace(" ",''))
    #the above line can be used to scrape the next line and vice versa
    #the below line is saying grab the index of the next strong tag
    d["Baths"]=(item("strong", {})[1].text.replace("\n", "").replace(" ",''))
    try:
# print(item("strong", {})[2].text.replace("\n", "").replace(" ",'')) #get the 3rd strong tag
        d["Property Size"]=(item.find_all("div", {"class": "property-sqft"})[0].find("strong").text.replace("\n", "").replace(" ",''))
    except:
        d["Property Size"]=None
        
    #     print(item.find_all("a", {"class":"listing-price"})[0].text.replace("\n", "").replace(" ",''))
    d["Prices"]=item.find("a", {"class":"listing-price"}).text.replace("\n", "").replace(" ",'')
    print("\n")
    l.append(d)
    
#find_all will take an index
#find does not need an index

In [237]:
print(l)
len(l)

[{'Addresses': '1665KeavyRoad', 'Beds': '3', 'Baths': '2', 'Property Size': '1,416', 'Prices': '$234,900'}, {'Addresses': '5460SlateLickRoad', 'Beds': '4', 'Baths': '3', 'Property Size': '5,500', 'Prices': '$749,900'}, {'Addresses': '115SwissColonyLane', 'Beds': '3', 'Baths': '2', 'Property Size': '1,787', 'Prices': '$159,900'}, {'Addresses': '1033EastFourthStreet', 'Beds': '3', 'Baths': '3', 'Property Size': '4,944', 'Prices': '$449,900'}, {'Addresses': '216ArmoryStreetStreet', 'Beds': '2', 'Baths': '1', 'Property Size': '1,188', 'Prices': '$164,500'}, {'Addresses': '913BullockDrive', 'Beds': '2', 'Baths': '1', 'Property Size': '806', 'Prices': '$45,000'}, {'Addresses': '1600TerrellsCreek', 'Beds': '3', 'Baths': '3', 'Property Size': '3,440', 'Prices': '$490,000'}, {'Addresses': '2783OldWhitleyRoad', 'Beds': '3', 'Baths': '2', 'Property Size': '1,861', 'Prices': '$245,000'}, {'Addresses': '67CumberlandWay', 'Beds': '3', 'Baths': '2', 'Property Size': '1,607', 'Prices': '$209,900'}, {'Addresses': '604LaurelRoad', 'Beds': '2', 'Baths': '1', 'Property Size': '1,008', 'Prices': '$63,900'}, {'Addresses': '604LaurelRoad', 'Beds': '2', 'Baths': '1', 'Property Size': '1,008', 'Prices': '$63,900'}, {'Addresses': '265AutumnDrive', 'Beds': '5', 'Baths': '2', 'Property Size': '2,200', 'Prices': '$259,900'}, {'Addresses': '1078&1070BowmanRoad4', 'Beds': '8', 'Baths': '4', 'Property Size': '3,846', 'Prices': '$399,900'}, {'Addresses': '1712LaurelLakeRoadNorth', 'Beds': '3', 'Baths': '2', 'Property Size': '1,568', 'Prices': '$225,000'}, {'Addresses': '1080BowmanRDRoad', 'Beds': '2', 'Baths': '1', 'Property Size': '860', 'Prices': '$199,900'}, {'Addresses': '201SlateLickStreetStreet', 'Beds': '3', 'Baths': '1', 'Property Size': '1,513', 'Prices': '$159,990'}, {'Addresses': '1652NevadaAvenue', 'Beds': '6', 'Baths': '6', 'Property Size': None, 'Prices': '$429,900'}, {'Addresses': '1430KeavyRoad', 'Beds': '3', 'Baths': '1', 'Property Size': '1,932', 'Prices': '$65,000'}, {'Addresses': '1000NewSalemRoad', 'Beds': '4', 'Baths': '3', 'Property Size': '2,240', 'Prices': '$399,900'}, {'Addresses': '1072WhitsonSchoolRoad', 'Beds': '3', 'Baths': '2', 'Property Size': '2,505', 'Prices': '$379,900'}]

20

In [238]:
import pandas
df=pandas.DataFrame(l) #passing our list of dictionary or objects to a pandas dataframe 
df

                   Addresses Beds Baths Property Size    Prices
0              1665KeavyRoad    3     2         1,416  $234,900
1          5460SlateLickRoad    4     3         5,500  $749,900
2         115SwissColonyLane    3     2         1,787  $159,900
3       1033EastFourthStreet    3     3         4,944  $449,900
4      216ArmoryStreetStreet    2     1         1,188  $164,500
5            913BullockDrive    2     1           806   $45,000
6          1600TerrellsCreek    3     3         3,440  $490,000
7         2783OldWhitleyRoad    3     2         1,861  $245,000
8            67CumberlandWay    3     2         1,607  $209,900
9              604LaurelRoad    2     1         1,008   $63,900
10             604LaurelRoad    2     1         1,008   $63,900
11            265AutumnDrive    5     2         2,200  $259,900
12      1078&1070BowmanRoad4    8     4         3,846  $399,900
13   1712LaurelLakeRoadNorth    3     2         1,568  $225,000
14          1080BowmanRDRoad    2     1           860  $199,900
15  201SlateLickStreetStreet    3     1         1,513  $159,990
16          1652NevadaAvenue    6     6          None  $429,900
17             1430KeavyRoad    3     1         1,932   $65,000
18          1000NewSalemRoad    4     3         2,240  $399,900
19     1072WhitsonSchoolRoad    3     2         2,505  $379,900

In [239]:
df.to_csv("data.csv") #saving it as a csv file

In [240]:
##iterating allthe pages to get all the listing from our search on century21 site

In [269]:
l=[]
base_url="https://www.century21.com/real-estate/london-ky/LCKYLONDON/?p="
for page in range(1,4,1):
    
    request=requests.get(base_url + str(page))
    data=request.content
    soup=BeautifulSoup(data, "html.parser")

    for item in card:
        d={} #when dictionary is global the on each iteration, the dictionary contents gets replaced so you end up with only one data

        d["Addresses"]=(item.find_all("div", {"class": "property-address"})[0].text.replace("\n", "").replace(" ",''))

        d["Beds"]=(item.find("div", {"class":"property-beds"}).find("strong").text.replace("\n", "").replace(" ",''))
        #the above line can be used to scrape the next line and vice versa
        #the below line is saying grab the index of the next strong tag
        d["Baths"]=(item("strong", {})[1].text.replace("\n", "").replace(" ",''))
        try:
    # print(item("strong", {})[2].text.replace("\n", "").replace(" ",'')) #get the 3rd strong tag
            d["Property Size"]=(item.find_all("div", {"class": "property-sqft"})[0].find("strong").text.replace("\n", "").replace(" ",''))
        except:
            d["Property Size"]=None

        #     print(item.find_all("a", {"class":"listing-price"})[0].text.replace("\n", "").replace(" ",''))
        d["Prices"]=item.find("a", {"class":"listing-price"}).text.replace("\n", "").replace(" ",'')
        print("\n")
        l.append(d)
l #print out the list of objects

[{'Addresses': '1665KeavyRoad',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '1,416',
  'Prices': '234,900'},
 {'Addresses': '5460SlateLickRoad',
  'Beds': '4',
  'Baths': '3',
  'Property Size': '5,500',
  'Prices': '749,900'},
 {'Addresses': '115SwissColonyLane',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '1,787',
  'Prices': '159,900'},
 {'Addresses': '1033EastFourthStreet',
  'Beds': '3',
  'Baths': '3',
  'Property Size': '4,944',
  'Prices': '449,900'},
 {'Addresses': '216ArmoryStreetStreet',
  'Beds': '2',
  'Baths': '1',
  'Property Size': '1,188',
  'Prices': '164,500'},
 {'Addresses': '913BullockDrive',
  'Beds': '2',
  'Baths': '1',
  'Property Size': '806',
  'Prices': '45,000'},
 {'Addresses': '1600TerrellsCreek',
  'Beds': '3',
  'Baths': '3',
  'Property Size': '3,440',
  'Prices': '490,000'},
 {'Addresses': '2783OldWhitleyRoad',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '1,861',
  'Prices': '245,000'},
 {'Addresses': '67CumberlandWay',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '1,607',
  'Prices': '209,900'},
 {'Addresses': '604LaurelRoad',
  'Beds': '2',
  'Baths': '1',
  'Property Size': '1,008',
  'Prices': '63,900'},
 {'Addresses': '604LaurelRoad',
  'Beds': '2',
  'Baths': '1',
  'Property Size': '1,008',
  'Prices': '63,900'},
 {'Addresses': '265AutumnDrive',
  'Beds': '5',
  'Baths': '2',
  'Property Size': '2,200',
  'Prices': '259,900'},
 {'Addresses': '1078&1070BowmanRoad4',
  'Beds': '8',
  'Baths': '4',
  'Property Size': '3,846',
  'Prices': '399,900'},
 {'Addresses': '1712LaurelLakeRoadNorth',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '1,568',
  'Prices': '225,000'},
 {'Addresses': '1080BowmanRDRoad',
  'Beds': '2',
  'Baths': '1',
  'Property Size': '860',
  'Prices': '199,900'},
 {'Addresses': '201SlateLickStreetStreet',
  'Beds': '3',
  'Baths': '1',
  'Property Size': '1,513',
  'Prices': '159,990'},
 {'Addresses': '1652NevadaAvenue',
  'Beds': '6',
  'Baths': '6',
  'Property Size': None,
  'Prices': '429,900'},
 {'Addresses': '1430KeavyRoad',
  'Beds': '3',
  'Baths': '1',
  'Property Size': '1,932',
  'Prices': '65,000'},
 {'Addresses': '1000NewSalemRoad',
  'Beds': '4',
  'Baths': '3',
  'Property Size': '2,240',
  'Prices': '399,900'},
 {'Addresses': '1072WhitsonSchoolRoad',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '2,505',
  'Prices': '379,900'},
 {'Addresses': '1665KeavyRoad',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '1,416',
  'Prices': '234,900'},
 {'Addresses': '5460SlateLickRoad',
  'Beds': '4',
  'Baths': '3',
  'Property Size': '5,500',
  'Prices': '749,900'},
 {'Addresses': '115SwissColonyLane',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '1,787',
  'Prices': '159,900'},
 {'Addresses': '1033EastFourthStreet',
  'Beds': '3',
  'Baths': '3',
  'Property Size': '4,944',
  'Prices': '449,900'},
 {'Addresses': '216ArmoryStreetStreet',
  'Beds': '2',
  'Baths': '1',
  'Property Size': '1,188',
  'Prices': '164,500'},
 {'Addresses': '913BullockDrive',
  'Beds': '2',
  'Baths': '1',
  'Property Size': '806',
  'Prices': '45,000'},
 {'Addresses': '1600TerrellsCreek',
  'Beds': '3',
  'Baths': '3',
  'Property Size': '3,440',
  'Prices': '490,000'},
 {'Addresses': '2783OldWhitleyRoad',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '1,861',
  'Prices': '245,000'},
 {'Addresses': '67CumberlandWay',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '1,607',
  'Prices': '209,900'},
 {'Addresses': '604LaurelRoad',
  'Beds': '2',
  'Baths': '1',
  'Property Size': '1,008',
  'Prices': '63,900'},
 {'Addresses': '604LaurelRoad',
  'Beds': '2',
  'Baths': '1',
  'Property Size': '1,008',
  'Prices': '63,900'},
 {'Addresses': '265AutumnDrive',
  'Beds': '5',
  'Baths': '2',
  'Property Size': '2,200',
  'Prices': '259,900'},
 {'Addresses': '1078&1070BowmanRoad4',
  'Beds': '8',
  'Baths': '4',
  'Property Size': '3,846',
  'Prices': '399,900'},
 {'Addresses': '1712LaurelLakeRoadNorth',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '1,568',
  'Prices': '225,000'},
 {'Addresses': '1080BowmanRDRoad',
  'Beds': '2',
  'Baths': '1',
  'Property Size': '860',
  'Prices': '199,900'},
 {'Addresses': '201SlateLickStreetStreet',
  'Beds': '3',
  'Baths': '1',
  'Property Size': '1,513',
  'Prices': '159,990'},
 {'Addresses': '1652NevadaAvenue',
  'Beds': '6',
  'Baths': '6',
  'Property Size': None,
  'Prices': '429,900'},
 {'Addresses': '1430KeavyRoad',
  'Beds': '3',
  'Baths': '1',
  'Property Size': '1,932',
  'Prices': '65,000'},
 {'Addresses': '1000NewSalemRoad',
  'Beds': '4',
  'Baths': '3',
  'Property Size': '2,240',
  'Prices': '399,900'},
 {'Addresses': '1072WhitsonSchoolRoad',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '2,505',
  'Prices': '379,900'},
 {'Addresses': '1665KeavyRoad',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '1,416',
  'Prices': '234,900'},
 {'Addresses': '5460SlateLickRoad',
  'Beds': '4',
  'Baths': '3',
  'Property Size': '5,500',
  'Prices': '749,900'},
 {'Addresses': '115SwissColonyLane',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '1,787',
  'Prices': '159,900'},
 {'Addresses': '1033EastFourthStreet',
  'Beds': '3',
  'Baths': '3',
  'Property Size': '4,944',
  'Prices': '449,900'},
 {'Addresses': '216ArmoryStreetStreet',
  'Beds': '2',
  'Baths': '1',
  'Property Size': '1,188',
  'Prices': '164,500'},
 {'Addresses': '913BullockDrive',
  'Beds': '2',
  'Baths': '1',
  'Property Size': '806',
  'Prices': '45,000'},
 {'Addresses': '1600TerrellsCreek',
  'Beds': '3',
  'Baths': '3',
  'Property Size': '3,440',
  'Prices': '490,000'},
 {'Addresses': '2783OldWhitleyRoad',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '1,861',
  'Prices': '245,000'},
 {'Addresses': '67CumberlandWay',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '1,607',
  'Prices': '209,900'},
 {'Addresses': '604LaurelRoad',
  'Beds': '2',
  'Baths': '1',
  'Property Size': '1,008',
  'Prices': '63,900'},
 {'Addresses': '604LaurelRoad',
  'Beds': '2',
  'Baths': '1',
  'Property Size': '1,008',
  'Prices': '63,900'},
 {'Addresses': '265AutumnDrive',
  'Beds': '5',
  'Baths': '2',
  'Property Size': '2,200',
  'Prices': '259,900'},
 {'Addresses': '1078&1070BowmanRoad4',
  'Beds': '8',
  'Baths': '4',
  'Property Size': '3,846',
  'Prices': '399,900'},
 {'Addresses': '1712LaurelLakeRoadNorth',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '1,568',
  'Prices': '225,000'},
 {'Addresses': '1080BowmanRDRoad',
  'Beds': '2',
  'Baths': '1',
  'Property Size': '860',
  'Prices': '199,900'},
 {'Addresses': '201SlateLickStreetStreet',
  'Beds': '3',
  'Baths': '1',
  'Property Size': '1,513',
  'Prices': '159,990'},
 {'Addresses': '1652NevadaAvenue',
  'Beds': '6',
  'Baths': '6',
  'Property Size': None,
  'Prices': '429,900'},
 {'Addresses': '1430KeavyRoad',
  'Beds': '3',
  'Baths': '1',
  'Property Size': '1,932',
  'Prices': '65,000'},
 {'Addresses': '1000NewSalemRoad',
  'Beds': '4',
  'Baths': '3',
  'Property Size': '2,240',
  'Prices': '399,900'},
 {'Addresses': '1072WhitsonSchoolRoad',
  'Beds': '3',
  'Baths': '2',
  'Property Size': '2,505',
  'Prices': '379,900'}]

In [272]:
import pandas
df=pandas.DataFrame(l) #passing our list of dictionary or objects to a pandas dataframe 
df

                   Addresses Beds Baths Property Size   Prices
0              1665KeavyRoad    3     2         1,416  234,900
1          5460SlateLickRoad    4     3         5,500  749,900
2         115SwissColonyLane    3     2         1,787  159,900
3       1033EastFourthStreet    3     3         4,944  449,900
4      216ArmoryStreetStreet    2     1         1,188  164,500
5            913BullockDrive    2     1           806   45,000
6          1600TerrellsCreek    3     3         3,440  490,000
7         2783OldWhitleyRoad    3     2         1,861  245,000
8            67CumberlandWay    3     2         1,607  209,900
9              604LaurelRoad    2     1         1,008   63,900
10             604LaurelRoad    2     1         1,008   63,900
11            265AutumnDrive    5     2         2,200  259,900
12      1078&1070BowmanRoad4    8     4         3,846  399,900
13   1712LaurelLakeRoadNorth    3     2         1,568  225,000
14          1080BowmanRDRoad    2     1           860  199,900
15  201SlateLickStreetStreet    3     1         1,513  159,990
16          1652NevadaAvenue    6     6          None  429,900
17             1430KeavyRoad    3     1         1,932   65,000
18          1000NewSalemRoad    4     3         2,240  399,900
19     1072WhitsonSchoolRoad    3     2         2,505  379,900
20             1665KeavyRoad    3     2         1,416  234,900
21         5460SlateLickRoad    4     3         5,500  749,900
22        115SwissColonyLane    3     2         1,787  159,900
23      1033EastFourthStreet    3     3         4,944  449,900
24     216ArmoryStreetStreet    2     1         1,188  164,500
25           913BullockDrive    2     1           806   45,000
26         1600TerrellsCreek    3     3         3,440  490,000
27        2783OldWhitleyRoad    3     2         1,861  245,000
28           67CumberlandWay    3     2         1,607  209,900
29             604LaurelRoad    2     1         1,008   63,900
30             604LaurelRoad    2     1         1,008   63,900
31            265AutumnDrive    5     2         2,200  259,900
32      1078&1070BowmanRoad4    8     4         3,846  399,900
33   1712LaurelLakeRoadNorth    3     2         1,568  225,000
34          1080BowmanRDRoad    2     1           860  199,900
35  201SlateLickStreetStreet    3     1         1,513  159,990
36          1652NevadaAvenue    6     6          None  429,900
37             1430KeavyRoad    3     1         1,932   65,000
38          1000NewSalemRoad    4     3         2,240  399,900
39     1072WhitsonSchoolRoad    3     2         2,505  379,900
40             1665KeavyRoad    3     2         1,416  234,900
41         5460SlateLickRoad    4     3         5,500  749,900
42        115SwissColonyLane    3     2         1,787  159,900
43      1033EastFourthStreet    3     3         4,944  449,900
44     216ArmoryStreetStreet    2     1         1,188  164,500
45           913BullockDrive    2     1           806   45,000
46         1600TerrellsCreek    3     3         3,440  490,000
47        2783OldWhitleyRoad    3     2         1,861  245,000
48           67CumberlandWay    3     2         1,607  209,900
49             604LaurelRoad    2     1         1,008   63,900
50             604LaurelRoad    2     1         1,008   63,900
51            265AutumnDrive    5     2         2,200  259,900
52      1078&1070BowmanRoad4    8     4         3,846  399,900
53   1712LaurelLakeRoadNorth    3     2         1,568  225,000
54          1080BowmanRDRoad    2     1           860  199,900
55  201SlateLickStreetStreet    3     1         1,513  159,990
56          1652NevadaAvenue    6     6          None  429,900
57             1430KeavyRoad    3     1         1,932   65,000
58          1000NewSalemRoad    4     3         2,240  399,900
59     1072WhitsonSchoolRoad    3     2         2,505  379,900

In [273]:
df.to_csv("century21.csv")

In [274]:
df

                   Addresses Beds Baths Property Size   Prices
0              1665KeavyRoad    3     2         1,416  234,900
1          5460SlateLickRoad    4     3         5,500  749,900
2         115SwissColonyLane    3     2         1,787  159,900
3       1033EastFourthStreet    3     3         4,944  449,900
4      216ArmoryStreetStreet    2     1         1,188  164,500
5            913BullockDrive    2     1           806   45,000
6          1600TerrellsCreek    3     3         3,440  490,000
7         2783OldWhitleyRoad    3     2         1,861  245,000
8            67CumberlandWay    3     2         1,607  209,900
9              604LaurelRoad    2     1         1,008   63,900
10             604LaurelRoad    2     1         1,008   63,900
11            265AutumnDrive    5     2         2,200  259,900
12      1078&1070BowmanRoad4    8     4         3,846  399,900
13   1712LaurelLakeRoadNorth    3     2         1,568  225,000
14          1080BowmanRDRoad    2     1           860  199,900
15  201SlateLickStreetStreet    3     1         1,513  159,990
16          1652NevadaAvenue    6     6          None  429,900
17             1430KeavyRoad    3     1         1,932   65,000
18          1000NewSalemRoad    4     3         2,240  399,900
19     1072WhitsonSchoolRoad    3     2         2,505  379,900
20             1665KeavyRoad    3     2         1,416  234,900
21         5460SlateLickRoad    4     3         5,500  749,900
22        115SwissColonyLane    3     2         1,787  159,900
23      1033EastFourthStreet    3     3         4,944  449,900
24     216ArmoryStreetStreet    2     1         1,188  164,500
25           913BullockDrive    2     1           806   45,000
26         1600TerrellsCreek    3     3         3,440  490,000
27        2783OldWhitleyRoad    3     2         1,861  245,000
28           67CumberlandWay    3     2         1,607  209,900
29             604LaurelRoad    2     1         1,008   63,900
30             604LaurelRoad    2     1         1,008   63,900
31            265AutumnDrive    5     2         2,200  259,900
32      1078&1070BowmanRoad4    8     4         3,846  399,900
33   1712LaurelLakeRoadNorth    3     2         1,568  225,000
34          1080BowmanRDRoad    2     1           860  199,900
35  201SlateLickStreetStreet    3     1         1,513  159,990
36          1652NevadaAvenue    6     6          None  429,900
37             1430KeavyRoad    3     1         1,932   65,000
38          1000NewSalemRoad    4     3         2,240  399,900
39     1072WhitsonSchoolRoad    3     2         2,505  379,900
40             1665KeavyRoad    3     2         1,416  234,900
41         5460SlateLickRoad    4     3         5,500  749,900
42        115SwissColonyLane    3     2         1,787  159,900
43      1033EastFourthStreet    3     3         4,944  449,900
44     216ArmoryStreetStreet    2     1         1,188  164,500
45           913BullockDrive    2     1           806   45,000
46         1600TerrellsCreek    3     3         3,440  490,000
47        2783OldWhitleyRoad    3     2         1,861  245,000
48           67CumberlandWay    3     2         1,607  209,900
49             604LaurelRoad    2     1         1,008   63,900
50             604LaurelRoad    2     1         1,008   63,900
51            265AutumnDrive    5     2         2,200  259,900
52      1078&1070BowmanRoad4    8     4         3,846  399,900
53   1712LaurelLakeRoadNorth    3     2         1,568  225,000
54          1080BowmanRDRoad    2     1           860  199,900
55  201SlateLickStreetStreet    3     1         1,513  159,990
56          1652NevadaAvenue    6     6          None  429,900
57             1430KeavyRoad    3     1         1,932   65,000
58          1000NewSalemRoad    4     3         2,240  399,900
59     1072WhitsonSchoolRoad    3     2         2,505  379,900

In [276]:
from bokeh.plotting import show, output_file, figure

p=figure(width=600, height=500)

x = df["Beds"].astype(int)

y= df["Baths"]
p.line(x, y)

show(p)
output_file("century21.html")

ValueError: invalid literal for int() with base 10: '234,900'